/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>, '/Home/HeaderSelection' | '/Home/Library' | '/Home/MapShow' | '/Home/Slogan'>,
    '/Home/HeaderSelection': RouteRecordInfo<'/Home/HeaderSelection', '/Home/HeaderSelection', Record<never, never>, Record<never, never>>,
    '/Home/Library': RouteRecordInfo<'/Home/Library', '/Home/Library', Record<never, never>, Record<never, never>>,
    '/Home/MapShow': RouteRecordInfo<'/Home/MapShow', '/Home/MapShow', Record<never, never>, Record<never, never>>,
    '/Home/Slogan': RouteRecordInfo<'/Home/Slogan', '/Home/Slogan', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Home.vue': {
      routes: '/Home' | '/Home/HeaderSelection' | '/Home/Library' | '/Home/MapShow' | '/Home/Slogan'
      views: 'default'
    }
    'src/pages/Home/HeaderSelection.vue': {
      routes: '/Home/HeaderSelection'
      views: never
    }
    'src/pages/Home/Library.vue': {
      routes: '/Home/Library'
      views: never
    }
    'src/pages/Home/MapShow.vue': {
      routes: '/Home/MapShow'
      views: never
    }
    'src/pages/Home/Slogan.vue': {
      routes: '/Home/Slogan'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
